env: prod
http:
  host: 0.0.0.0
  port: 8100
security:
  api_sign:
    app_key: cheemshappy_pay
    app_security: cheemshappy_pay888
  jwt:
    key: 1QQ123TSEcr12389fw8prOaObmrch8
data:
  mysql:
    user: root:xxxx@tcp(xxxxx:7002)/cheemshappypay?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: xxxxx:6000
    password: "xxxx"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: info
  encoding: json # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
